name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup environment
      working-directory: scripts
      run: ./setupAll.sh
      shell: bash

    - name: Testing
      shell: bash
      working-directory: scripts
      run: ./enableTesting.sh
